title: Zersetzte Staaten – Die Akten der Macht
description: Ein dokumentarisches Archiv verdeckter Einflussnahme (1945–heute)
markdown: kramdown
theme: null

# WICHTIG für GitHub Pages Project Site:
url: "https://bozart-army.github.io"
baseurl: "/zersetzte-staaten-site"

plugins:
  - jekyll-relative-links
